"""HTML report writer — generates a self-contained threat report."""

import html
import os
from typing import Any, Dict, List

_SEVERITY_COLORS = {
    "critical": "#c0392b",
    "high": "#e67e22",
    "medium": "#f1c40f",
    "low": "#2ecc71",
    "benign": "#95a5a6",
}

_HTML_HEAD = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>MailFort Threat Report</title>
<style>
  body { font-family: 'Segoe UI', Arial, sans-serif; background: #f5f6fa; color: #2d3436; margin: 0; padding: 20px; }
  h1 { color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 8px; }
  .summary { background: #fff; border-radius: 8px; padding: 16px; margin-bottom: 24px; box-shadow: 0 2px 6px rgba(0,0,0,.08); }
  .summary span { font-weight: bold; }
  table { width: 100%; border-collapse: collapse; background: #fff; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 6px rgba(0,0,0,.08); margin-bottom: 24px; }
  th { background: #2c3e50; color: #fff; padding: 10px 14px; text-align: left; font-size: 13px; }
  td { padding: 9px 14px; border-bottom: 1px solid #ecf0f1; font-size: 13px; vertical-align: top; }
  tr:last-child td { border-bottom: none; }
  .badge { display: inline-block; padding: 3px 9px; border-radius: 12px; color: #fff; font-size: 11px; font-weight: bold; text-transform: uppercase; }
  .reason-list { margin: 0; padding-left: 18px; }
  .reason-list li { margin-bottom: 2px; }
  footer { color: #95a5a6; font-size: 12px; text-align: center; margin-top: 30px; }
</style>
</head>
<body>
<h1>MailFort Threat Report</h1>
"""

_HTML_FOOT = """<footer>Generated by MailFort &mdash; PhishFinder threat-analysis pipeline</footer>
</body></html>
"""


def write_html_report(cases: List[Dict[str, Any]], path: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True) if os.path.dirname(path) else None

    counts: Dict[str, int] = {}
    for case in cases:
        sev = case.get("verdict", {}).get("severity", "benign")
        counts[sev] = counts.get(sev, 0) + 1

    parts = [_HTML_HEAD]

    # Summary bar
    parts.append('<div class="summary"><b>Scan summary</b> &mdash; ')
    parts.append(f'{len(cases)} message(s) scanned. ')
    for sev, cnt in sorted(counts.items(), key=lambda x: ["critical","high","medium","low","benign"].index(x[0]) if x[0] in ["critical","high","medium","low","benign"] else 99):
        color = _SEVERITY_COLORS.get(sev, "#aaa")
        parts.append(
            f'<span class="badge" style="background:{color}">{sev}: {cnt}</span> '
        )
    parts.append("</div>\n")

    # Main table
    parts.append("""
<table>
<thead><tr>
  <th>Message ID</th><th>Sender</th><th>Subject</th><th>Provider</th>
  <th>Score</th><th>Severity</th><th>Action</th><th>Reasons</th>
</tr></thead>
<tbody>
""")

    for case in cases:
        m = case.get("message", {})
        v = case.get("verdict", {})
        p = case.get("policy", {})
        sev = v.get("severity", "benign")
        color = _SEVERITY_COLORS.get(sev, "#aaa")
        reasons_html = "<ul class='reason-list'>" + "".join(
            f"<li>{html.escape(r)}</li>" for r in v.get("reasons", [])[:5]
        ) + "</ul>"

        parts.append(f"""<tr>
  <td style="font-family:monospace;font-size:11px">{html.escape(str(m.get('message_id',''))[:16])}</td>
  <td>{html.escape(str(m.get('sender',''))[:50])}</td>
  <td>{html.escape(str(m.get('subject',''))[:60])}</td>
  <td>{html.escape(str(m.get('provider','')))} </td>
  <td><b>{v.get('final_score', 0)}</b><br><small>s:{v.get('static_score',0)} d:{v.get('dynamic_score',0)}</small></td>
  <td><span class="badge" style="background:{color}">{sev}</span></td>
  <td>{html.escape(str(p.get('action','allow')))}</td>
  <td>{reasons_html}</td>
</tr>
""")

    parts.append("</tbody></table>\n")
    parts.append(_HTML_FOOT)

    with open(path, "w", encoding="utf-8") as f:
        f.write("".join(parts))
